simple_salesforce/__init__.py,sha256=EFqMzaPXfh6chmTaMidlKB7db245LxLXlrXp74nnm6I,538
simple_salesforce/api.py,sha256=KKiSiCBCsQUikOvvuolo5H6AB8C84XCNlcHWWAH1uBY,29107
simple_salesforce/bulk.py,sha256=kCyd3aYgbQ2yakfDjswvZ0ylip9D6EdRbRM4fF3u4lg,9108
simple_salesforce/exceptions.py,sha256=iFLU_n_KSb9r5mZkCADvNQlLTyVDZy51bAdsTHHX9Gk,3406
simple_salesforce/login.py,sha256=VF8sF0PBODhvLGpJ2lReL1xqSwHSI2Dsn_WRm5pMInw,6843
simple_salesforce/util.py,sha256=Ur7grJowssrJqChx2JYlZbdgvE4ByQMO6DWIeCX062Y,2515
simple_salesforce-0.73.0.dist-info/DESCRIPTION.rst,sha256=pDyVWbsOvVjJPmwCRtNL0Oqu1C6ycBZOovHbClUcsGA,13009
simple_salesforce-0.73.0.dist-info/METADATA,sha256=MyAsXBnnbrg3sQtv_9RTdzpWGaawy4bJ-vi9VnfUibs,14065
simple_salesforce-0.73.0.dist-info/RECORD,,
simple_salesforce-0.73.0.dist-info/WHEEL,sha256=o2k-Qa-RMNIJmUdIc7KU6VWR_ErNRbWNlxDIpl7lm34,110
simple_salesforce-0.73.0.dist-info/metadata.json,sha256=Mcti7XLhRpAlxkh-LdtWhHYwrR3GX2eVIbiq9xVlBKg,1324
simple_salesforce-0.73.0.dist-info/top_level.txt,sha256=Hp1fBgmvtDXI6cwYWbFI72MRAeisTCrFHBY9uWsN1Kk,18
simple_salesforce-0.73.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
simple_salesforce/__init__.pyc,,
simple_salesforce/api.pyc,,
simple_salesforce/exceptions.pyc,,
simple_salesforce/bulk.pyc,,
simple_salesforce/login.pyc,,
simple_salesforce/util.pyc,,
